### ISSUE TITLE
[Feature] Profile

### ISSUE THREAD

**Issue by kxxt** [kxxt/tracexec#5]
Allow users to load settings from  `~/.config/tracexec/config.toml`.

**Comment by kxxt** [comment]
It need to be documented that the config format might be changed in an incompatible way between minor versions since we haven't reached 1.0 yet.

**Comment by kxxt** [comment]
> Hey, I was looking at possibly having a go at implementing this. Is this project open to PRs?

Yes. PRs are welcome. ☺️

**Comment by kxxt** [comment]
Hi @GeorgeMuscat, are you still interested in implementing this feature 🤗? If not, I might do it in the next few days.

**Comment by GeorgeMuscat** [comment]
I had a weak attempt but realised I wasn't familiar enough with the project and the design decisions to do it properly.

Might be best if you implement it. I will watch this issue and will have a look at your PR when you're done so I can get an idea of how you would want this solved. Thanks!
